logging:
  level:
    com.sevensignal.gateway_api: DEBUG
    org.springframework.security: TRACE
    org.springframework.boot.autoconfigure.web: TRACE
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: TRACE
    org.springframework.web.reactive: TRACE
    reactor.netty: DEBUG
    org.springframework.web.HttpLogging: TRACE

spring:
  cloud:
    gateway:
      httpserver:
        wiretap: true
      httpclient:
        wiretap: true